pub mod command;
pub mod database;
pub mod editor_mode;
pub mod embedding_client;
pub mod embedding_config;
pub mod embedding_indexer;
pub mod frontmatter;
pub mod markdown;
pub mod note_buffer;
pub mod note_file;
pub mod notes_config;
pub mod semantic_search;
pub mod text_chunker;

pub use command::{CommandParser, EditorAction, KeyModifiers};
pub use database::{NotesDatabase, SearchResult};
pub use editor_mode::EditorMode;
pub use embedding_client::{EmbeddingClient, EmbeddingProvider};
pub use embedding_config::{EmbeddingConfig, IndexStats};
pub use embedding_indexer::{EmbeddingIndexer, IndexProgress, ProgressCallback};
pub use frontmatter::{extract_all_tags, extract_inline_tags, extract_tags};
pub use markdown::{MarkdownParser, StyleType};
pub use note_buffer::NoteBuffer;
pub use note_file::{NoteFile, NotesDirectory};
pub use notes_config::NotesConfig;
pub use semantic_search::SearchResult as SemanticSearchResult;
pub use semantic_search::{SearchOptions, SemanticSearch};
pub use text_chunker::{ChunkConfig, TextChunk, TextChunker};
